---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app1-deploy
  name: app1-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app1-deploy
    spec:
      containers:
      - image: rabbanidocker/app1
        name: app1
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: node01
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app1-deploy
  name: app1-deploy-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app1-deploy
  type: NodePort
status:
  loadBalancer: {}
