apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app2-deploy
  name: app2-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app2-deploy
    spec:
      containers:
      - image: rabbanidocker/app2
        name: app2
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: node2
