apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app2-deploy
  name: app2-deploy-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app2-deploy
status:
  loadBalancer: {}
---
