pipeline {
    agent any
    environment {
        SHA = sh(returnStdout: true, script: "git rev-parse --short=10 HEAD").trim()
    }
	
    stages {
        stage('SCM Checkout'){
            steps {
                git branch: 'master', url: 'https://github.com/rabbanigithub/2-tier-app-on-kubernetes.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh "docker build -t rabbanidocker/app1:${SHA} -f ./app1/build/Dockerfile ."
            }
        }
        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerHubCredential', usernameVariable: 'dockerHubUser', passwordVariable: 'dockerHubPass')]) {
                sh 'echo ${dockerHubPass} | docker login -u ${dockerHubUser} --password-stdin'
                }
                sh 'docker push rabbanidocker/app1:${SHA}'
            }
        }
    }
}
