apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app1-deploy
  name: app1-deploy-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app1-deploy
  type: NodePort
status:
  loadBalancer: {}
