apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web-deploy
  name: web-deploy-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-deploy
  type: NodePort
status:
  loadBalancer: {}
