IMAGE_NAME = "ubuntu/focal64"
N = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end
      
    config.vm.define "controlplane" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "10.11.12.30"
        master.vm.hostname = "controlplane"
        master.vm.provision "ansible" do |ansible|
          ansible.playbook = "k8s-install/master-playbook.yml"
            ansible.extra_vars = {
                node_ip: "10.11.12.30",
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "10.11.12.#{i + 30}"
            node.vm.hostname = "node-#{i}"
#            node.vm.provision "ansible" do |ansible|
#                ansible.playbook = "kubernetes-setup/node-playbook.yml"
#                ansible.extra_vars = {
#                    node_ip: "10.11.12.#{i + 30}",
#                }
#            end
        end
    end
end
